version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - 7017:27017
    volumes:
      - db:/data/db
    env_file:
      - .env
    networks:
      - mongodb
volumes:
  db:
networks:
  mongodb:
    driver: bridge
