const CLIENT_URL = process.env.BASE_URL
const ACTIVE_TOKEN_SECRET = process.env.ACTIVE_TOKEN_SECRET
const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET
const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET

export { CLIENT_URL, ACTIVE_TOKEN_SECRET, ACCESS_TOKEN_SECRET, REFRESH_TOKEN_SECRET }
